### ISSUE TITLE
Popover form not submitting

### ISSUE THREAD

**Issue by cluwong** [kartik-v/yii2-popover-x#15]
Implemented a form similar to 'advanced html content (forms) with popover footer' example on the page. The form would not submit. 

On inspecting source code, I noticed that the popover box and its content is placed outside the form tag at the end of html page. Could this be the reason why since the form elements and submit button are outside the form tag?

Tried work around solution by putting ActiveForm::begin() and  ActiveForm::end() between PopoverX::begin() and PopoverX::end() instead, and can't put submit button in footer property of PopoverX widget. The form then submits. Is the example incorrect or is this a bug?

Using Yii 2.0.11.2, PopoverX V1.3.3, bootstrap popover-x V1.4.3.

**Comment by kartik-v** [comment]
Yes the example needs to be corrected. This is because the popover modal is being appended to the document `body` for addressing another issue.

Immediately you can just render the form within Popover body including the submit buttons as you mentioned. 

Will update the example for including footer based form buttons a bit later.

**Comment by kartik-v** [comment]
The example has been corrected now. You can cross the last example in [popover-x demo usage section](http://demos.krajee.com/popover-x#usage).
